[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
nixpkgsVersion = "nixos-22-11"

[[nixpacks.phases.setup]]
nixPkgs = ["nodejs-18_x"]

[nixpacks.phases.install]
cmds = ["npm ci"]

[nixpacks.phases.build]
cmds = ["npm run build"]

